"""
Employee Performance Analysis

Email: 25ds1000231@ds.study.iitm.ac.in
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def main():
    # 1. Load the employee data from CSV
    # Make sure this file exists in the same folder:
    # employee_id,department,region,performance_score,years_experience,satisfaction_rating
    df = pd.read_csv("employee_performance.csv")

    print("Sample of the dataset (first 5 rows):")
    print(df.head(), "\n")

    # 2. Calculate the frequency count for the "Sales" department
    sales_count = (df["department"] == "Sales").sum()
    print(f"Number of employees in the Sales department: {sales_count}")

    # 3. Create a histogram (countplot) for the distribution of departments
    plt.figure(figsize=(8, 5))
    sns.countplot(x="department", data=df)
    plt.title("Employee Count by Department")
    plt.xlabel("Department")
    plt.ylabel("Number of Employees")
    plt.xticks(rotation=45)
    plt.tight_layout()

    chart_filename = "histogram.png"
    plt.savefig(chart_filename)
    plt.close()

    # 4. Create an HTML file that includes:
    #    - your email
    #    - Sales department frequency count
    #    - the histogram image
    html_filename = "employee_performance.html"
    with open(html_filename, "w", encoding="utf-8") as f:
        f.write("<!DOCTYPE html>\n<html>\n<head>\n")
        f.write("<meta charset='UTF-8'>\n")
        f.write("<title>Employee Performance Analysis</title>\n")
        f.write("</head>\n<body>\n")

        f.write("<h1>Employee Performance Analysis</h1>\n")
        f.write("<p>This HTML report was generated by a Python script.</p>\n")

        # Email for verification
        f.write("<p><strong>Email:</strong> 25ds1000231@ds.study.iitm.ac.in</p>\n")

        # Sales count clearly written in HTML (so the checker finds it)
        f.write(
            f"<p>Number of employees in the "
            f"<strong>Sales</strong> department: "
            f"<strong>{sales_count}</strong></p>\n"
        )

        # Embed the histogram image
        f.write("<h2>Department Distribution</h2>\n")
        f.write(f"<img src='{chart_filename}' alt='Department distribution histogram'>\n")

        f.write("</body>\n</html>\n")

    print(f"\nHTML report generated: {html_filename}")
    print(f"Chart image saved as: {chart_filename}")


if __name__ == "__main__":
    main()
