"""
Employee Performance Analysis - Department Distribution

Author: 25ds1000231
Email: 25ds1000231@ds.study.iitm.ac.in
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def main():
    # 1. Create a synthetic dataset with 100 employees
    np.random.seed(42)  # for reproducibility

    departments = ["Sales", "Engineering", "HR", "Marketing", "Finance", "Support"]
    regions = ["North", "South", "East", "West"]

    data = []
    for emp_id in range(1, 101):  # 100 employees
        dept = np.random.choice(departments)
        region = np.random.choice(regions)
        # Performance score between 0 and 100 (clipped normal)
        perf_score = np.random.normal(loc=75, scale=10)
        perf_score = max(0, min(100, perf_score))

        data.append(
            {
                "EmployeeID": emp_id,
                "Department": dept,
                "Region": region,
                "PerformanceScore": round(perf_score, 1),
            }
        )

    df = pd.DataFrame(data)

    # (Optional) Show first 5 rows if you want to verify
    print("Sample of the dataset (first 5 rows):")
    print(df.head(), "\n")

    # 2. Calculate the frequency count for the "Sales" department
    sales_count = (df["Department"] == "Sales").sum()
    print(f"Number of employees in the Sales department: {sales_count}")

    # 3. Create a histogram (count plot) for the distribution of departments
    plt.figure(figsize=(8, 6))
    sns.countplot(x="Department", data=df)
    plt.title("Employee Count by Department")
    plt.xlabel("Department")
    plt.ylabel("Number of Employees")
    plt.xticks(rotation=45)
    plt.tight_layout()

    # Save the chart as an image
    chart_filename = "departments_hist.png"
    plt.savefig(chart_filename)
    plt.close()

    # 4. Create an HTML file that includes the email, Sales count, and the chart
    html_filename = "employee_performance.html"
    with open(html_filename, "w", encoding="utf-8") as f:
        f.write("<!DOCTYPE html>\n<html>\n<head>\n")
        f.write("<meta charset='UTF-8'>\n")
        f.write("<title>Employee Performance Analysis</title>\n")
        f.write("</head>\n<body>\n")
        f.write("<h1>Employee Performance Analysis</h1>\n")
        f.write("<p>This HTML file was generated by a Python script created using ChatGPT.</p>\n")
        f.write("<p><strong>Email for verification:</strong> 25ds1000231@ds.study.iitm.ac.in</p>\n")
        f.write(
            f"<p>Number of employees in the <strong>Sales</strong> department: "
            f"<strong>{sales_count}</strong></p>\n"
        )
        f.write(
            f"<h2>Department Distribution Histogram</h2>\n"
            f"<img src='{chart_filename}' alt='Department distribution histogram'>\n"
        )
        f.write("</body>\n</html>\n")

    print(f"\nHTML report generated: {html_filename}")
    print(f"Chart image saved as: {chart_filename}")


if __name__ == "__main__":
    main()
